# Generated by Django 3.2.4 on 2022-09-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
