# Generated by Django 3.2.4 on 2022-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=2000)),
                ('myfile', models.ImageField(default='', upload_to='static/profile/')),
            ],
        ),
    ]
