# Generated by Django 3.2.4 on 2022-09-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
